name = "QtTobubus"
author = "shibukawa.yoshiki"
organization = ""
license = "The MIT License (MIT)"
qtmodules = ["Core", "Network", "Concurrent"]
requires = ["github.com/qtpm/QtCBOR"]
version = [0, 1, 0]
project_start_year = 2016
